### ISSUE TITLE
This is quite amazing. And the Install app example is just magic

### ISSUE THREAD

**Issue by cezarneaga** [sgrove/blog#49]
The authguardian is a dream come true. talking to hasura is in mother tongue :)  Had a few issues in Firefox with rules not being persisted and losing state. Css could be improved also got these weirdly wide screens because stuff expanded out of bounds :) Let me know if i can help with this.

```next-js-metadata
{"emotion":"amazed","user":{"bio":"","email":"","databaseId":645227,"login":"cezarneaga","id":"MDQ6VXNlcjY0NTIyNw==","name":"Cezar Neaga"}}
```

**Comment by cezarneaga** [comment]
ps: 还不错

**Comment by sgrove** [comment]
Thanks so much!

**Comment by sgrove** [comment]
Thanks so much!

**Comment by sgrove** [comment]
Thanks so much!

**Comment by sgrove** [comment]
Thanks so much!

**Comment by sgrove** [comment]
From plain javascript!

**Comment by sgrove** [comment]
Testing node.js integration - so slick!

**Comment by sgrove** [comment]
Thank you!

**Comment by sgrove** [comment]
Wow, plain js!

**Comment by sgrove** [comment]
Thanks so much!

**Comment by sgrove** [comment]
This is coming from react-query

**Comment by sgrove** [comment]
Up and up

**Comment by sgrove** [comment]
So complete!

**Comment by sgrove** [comment]
Coming live from react-query!

**Comment by sgrove** [comment]
Coming straight out Vue, CA

**Comment by sgrove** [comment]
Whhhhhat this, then?

**Comment by sgrove** [comment]
null

**Comment by sgrove** [comment]
null

**Comment by sgrove** [comment]
Gooooood evening there!

**Comment by sgrove** [comment]
null
