### ISSUE TITLE
Full best-of-breed vue-apollo apps with auth, real-time subscriptions, and more with just one click!

### ISSUE THREAD

**Issue by sgrove** [sgrove/blog#57]
不得不爱

**Comment by sgrove** [comment]
We love vue!

**Comment by sgrove** [comment]
Looking quite svelte...

**Comment by sgrove** [comment]
Looking quite svelte...

**Comment by sgrove** [comment]
Including component props...

**Comment by sgrove** [comment]
Including component props...

**Comment by sgrove** [comment]
Including component props...

**Comment by sgrove** [comment]
Including component props...

**Comment by sgrove** [comment]
Including component props...

**Comment by sgrove** [comment]
Including component props...

**Comment by sgrove** [comment]
Including component props...

**Comment by sgrove** [comment]
Including component props...

**Comment by sgrove** [comment]
Including component props...

**Comment by sgrove** [comment]
Including component props...

**Comment by sgrove** [comment]
Including component props...

**Comment by sgrove** [comment]
Including component props...

**Comment by jonas-kgomo** [comment]
some new string

**Comment by jonas-kgomo** [comment]
some new string
